# 使用官方 Python 运行时作为父镜像
FROM python:3.9-slim

# 设置工作目录
WORKDIR /app

# 将当前目录内容复制到容器的 /app 中
COPY . /app

# 安装项目依赖
RUN pip install --no-cache-dir -r requirements.txt


WORKDIR /app/app

# 运行应用
CMD ["gunicorn", "-w", "5", "-b", "0.0.0.0:8000", "--worker-class", "gevent","--worker-connections", "100",
"--preload","--max-requests","1000","--max-requests-jitter","200",
"--keep-alive", "10", "SimpleCaptcha:app"]
