version: '3.8'

services:
  ddddocr-api:
    build: .
    ports:
      - "23456:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    restart: always
    command: python /app/app/SimpleCaptcha.py
